// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/liuxianan1/workspace/youtil/node_modules/dumi/theme-default/slots/SearchBar/index.js';
export * from '/Users/liuxianan1/workspace/youtil/node_modules/dumi/theme-default/slots/SearchBar/index.js';
